[tool.black]
line-length = 100
extend-exclude = '''
(
  ^tilt_modules/
)
'''

[tool.ruff]
line-length = 100
exclude = ["tilt_modules"]

[tool.ruff.lint]
select = ["E","F","I","UP","N","B"]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["svc_1", "svc_2"]

[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
