apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: base
      version: ">=1.21.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
