apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 15m
  chart:
    spec:
      chart: istiod
      version: ">=1.21.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    pilot:
      autoscaleEnabled: true
