name: monorepo-ci
on:
  pull_request:
  push:
    branches: [main]

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-matrix.outputs.services }}
    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        shell: bash
        run: |
          set -euo pipefail
          if [ -d "services" ]; then
            MAP=$(
              ls -1 services 2>/dev/null \
              | sed 's#^#services/#' \
              | xargs -I{} sh -c '[ -f "{}/pyproject.toml" ] && echo {}' \
              | jq -R -s -c 'split("\n")|map(select(length>0))'
            )
          else
            MAP="[]"
          fi

          # Safety: if jq produced null (no lines), use empty array
          if [ "$MAP" = "null" ] || [ -z "$MAP" ]; then
            MAP="[]"
          fi

          echo "Discovered services matrix: $MAP"
          echo "services=$MAP" >> "$GITHUB_OUTPUT"
  test:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.discover.outputs.services) }}
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install uv
      - run: uv venv
      - run: uv pip install -e .[dev]
      - run: uv run ruff check .
      - run: uv run black --check .
      - run: uv run mypy .
      - run: uv run pytest
